spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?allowpublickeyretrieval=true
    username: shopping
    password: shop323

  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none